import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/footer"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="md:w-[50%] lg:w-[30%] m-auto max-md:w-[90%] font-sans">
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
